language: cpp
compiler: gcc

before_install:
- sudo apt-get -y install libboost-dev
- sudo apt-get -y install libboost-system-dev
- sudo apt-get -y install libboost-filesystem-dev
- sudo cp -r phat /usr/local/include/
- ls /usr/local/include/
- git clone https://github.com/GUDHI/gudhi-devel.git
- cd gudhi-devel
- mkdir build
- cd build
- cmake ..
- make
- make install
- sudo apt-get -y install libtbb-dev

script:
- cd time_test
- g++ test_diagram_computation.cpp -std=c++17 -Os -lpthread -fopenmp -ltbb -o test1
- ./test1