language: cpp
compiler: gcc

dist: bionic

before_install:
- sudo add-apt-repository -y ppa:boost-latest/ppa
- sudo apt-get update
- sudo apt-get install libboost1X.55-all-dev
- sudo apt-get -y install libboost-test-dev
- sudo apt-get -y install libboost-system-dev
- sudo apt-get -y install libboost-filesystem-dev
- sudo apt-get -y install libboost-thread-dev
- sudo apt-get -y install libboost-program-options-dev
- sudo cp -r phat /usr/local/include/
- ls /usr/local/include/
- sudo cp -r gudhi /usr/local/include/
- sudo apt-get -y install libtbb-dev

script:
- cd time_test
- g++ test_diagram_computation.cpp -std=c++17 -Os -lpthread -fopenmp -ltbb -o test1
- ./test1