language: cpp
compiler: gcc

dist: bionic

before_install:
- apt-search gudhi
- sudo apt-get -y install libphat-dev
- sudo apt-get -y install libtbb-dev
- sudo apt-get -y install libgudhi-dev

script:
- cd time_test
- g++ test_diagram_computation.cpp -std=c++17 -Os -lpthread -fopenmp -ltbb -o test1
- ./test1