language: cpp
compiler: gcc

dist: bionic

before_install:
- sudo apt-get -y install libboost-dev
- sudo apt-get -y install libboost-test-dev
- sudo apt-get -y install libboost-system-dev
- sudo apt-get -y install libboost-filesystem-dev
- sudo apt-get -y install libboost-thread-dev
- sudo apt-get -y install libboost-program-options-dev
- sudo apt-get -y install valgrind
- sudo cp -r dep/thread_pool/thread_pool /usr/local/include/
- sudo cp -r dep/thread_pool/thread_pool.hpp /usr/local/include/
- sudo cp -r dep/phat /usr/local/include/
- sudo cp -r dep/gudhi /usr/local/include/
- sudo apt-get -y install libtbb-dev

script:
- cd time_test
- g++ test_algorithm.cpp  -std=c++17 -Os -lpthread -lboost_system -fopenmp -ltbb -o testd_a_1
- valgrind --leak-check=full ./testd_a_1
- g++ test_ripser.cpp  -std=c++17 -Os -lpthread -lboost_system -fopenmp -ltbb -o test_r
- ./test_r
- g++ test_gudhi.cpp  -std=c++17 -Os -lpthread -lboost_system -fopenmp -ltbb -o test_g
- ./test_g
- g++ test_diagram_computation_v.cpp  -std=c++17 -Os -lpthread -lboost_system -fopenmp -ltbb -o testd_v_1
- valgrind --leak-check=full ./testd_v_1
- g++ test_diagram_computation.cpp  -std=c++17 -Os -lpthread -lboost_system -fopenmp -ltbb -o test_d_c
- ./test_d_c
