all:
	g++ test_gudhi.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_g_m
	g++ test_ripser.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_r_m
	g++ test_diagram_computation_v.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_dc_v
	g++ test_algorithm.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_a_v
	g++ test_diagram_computation.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_dc_m
	g++ example.cpp -std=c++17 -Os -lpthread -lboost_system -ltbb -o algo_r_m