all:
	g++ test_algorithm.cpp -std=c++17 -ltbb -Os -lomp -o algo_a_v
	g++ test_diagram_computation.cpp -std=c++17 -ltbb -Os -lomp -o algo_dc_m
	g++ test_diagram_computation_v.cpp -std=c++17 -ltbb -Os -lomp -o algo_dc_v
	g++ test_ripser.cpp -std=c++17 -ltbb -Os -lomp -o algo_r_m
	g++ test_gudhi.cpp -std=c++17 -ltbb -Os -lomp -o algo_g_m